In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.21.2'

In [3]:
pd.__version__

'1.3.3'

In [4]:
cars_dataset = pd.read_csv('data.csv')

In [5]:
cars_dataset.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [9]:
bmw_dataset = cars_dataset[cars_dataset['Make'] == 'BMW']
bmw_dataset.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [10]:
bmw_dataset['MSRP'].mean()

61546.76347305389

In [61]:
cars_dataset_after_2015 = cars_dataset[cars_dataset['Year'] >= 2015]
cars_dataset_after_2015.head()

Make       Model  Year                Engine Fuel Type  Engine HP  \
32  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41   BMW    2 Series  2016     premium unleaded (required)      240.0   
42   BMW    2 Series  2016     premium unleaded (required)      240.0   

    Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32               4.0            MANUAL  rear wheel drive              2.0   
33               4.0            MANUAL  rear wheel drive              2.0   
34               4.0            MANUAL  rear wheel drive              2.0   
41               4.0         AUTOMATIC  rear wheel drive              2.0   
42               4.0         AUTOMATIC  rear wheel drive              2.0   

       Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
32         Performance      Compact   Convertible           35        26   
33         Performance      Compact   Convertible           35        26   
34         Performance      Compact   Convertible           35        26   
41  Luxury,Performance      Compact         Coupe           35        23   
42              Luxury      Compact   Convertible           34        23   

    Popularity   MSRP  
32         819  27495  
33         819  24995  
34         819  28195  
41        3916  32850  
42        3916  38650

In [62]:
cars_dataset_after_2015['Engine HP'].isnull().sum()

51

In [63]:
round(cars_dataset_after_2015['Engine HP'].mean())

273

In [64]:
cars_dataset_after_2015['Engine HP'].fillna(value=274, inplace=True)

/usr/local/lib/python3.7/site-packages/pandas/core/generic.py:6392: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)


In [65]:
round(cars_dataset_after_2015['Engine HP'].mean())

273

In [33]:
cars_dataset['Make'].unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [34]:
rollsroyce_dataset = cars_dataset[cars_dataset['Make'] == 'Rolls-Royce']
rollsroyce_dataset.head()

Make            Model  Year             Engine Fuel Type  \
2921  Rolls-Royce         Corniche  2001  premium unleaded (required)   
3505  Rolls-Royce             Dawn  2016  premium unleaded (required)   
5275  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5276  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5277  Rolls-Royce  Ghost Series II  2016  premium unleaded (required)   

      Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921      325.0               8.0         AUTOMATIC  rear wheel drive   
3505      563.0              12.0         AUTOMATIC  rear wheel drive   
5275      563.0              12.0         AUTOMATIC  rear wheel drive   
5276      563.0              12.0         AUTOMATIC  rear wheel drive   
5277      563.0              12.0         AUTOMATIC  rear wheel drive   

      Number of Doors                 Market Category Vehicle Size  \
2921              2.0                   Exotic,Luxury        Large   
3505              2.0  Exotic,Luxury,High-Performance        Large   
5275              4.0       Exotic,Luxury,Performance        Large   
5276              4.0       Exotic,Luxury,Performance        Large   
5277              4.0       Exotic,Luxury,Performance        Large   

     Vehicle Style  highway MPG  city mpg  Popularity    MSRP  
2921   Convertible           15        10          86  359990  
3505   Convertible           19        12          86  335000  
5275         Sedan           21        13          86  286750  
5276         Sedan           21        13          86  319400  
5277         Sedan           21        13          86  295850

In [40]:
three_columns = rollsroyce_dataset[['Engine HP', 'Engine Cylinders', 'highway MPG']]

In [44]:
drop_three_columns = three_columns.drop_duplicates()

In [47]:
X = drop_three_columns.to_numpy()

In [48]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [53]:
XTX = np.matmul(np.transpose(X), X)

In [54]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [56]:
np.linalg.inv(XTX).sum()

0.032212320677486125

In [57]:
Y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [58]:
w_temp = np.matmul(np.linalg.inv(XTX), np.transpose(X))

In [59]:
w = np.matmul(w_temp, Y)

In [60]:
w

array([ 0.19989598, 31.02612262, 31.65378877])